- hosts: webservers
  become: true

  tasks:
    - name: Update APT repository targets to Focal Fossa
      become: true
      replace:
        path: "/etc/apt/sources.list"
        regexp: "disco"
        replace: "focal"

    - name: Update APT repository cache
      apt:
        update_cache: yes

    - name: Install Docker Prereqs
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools

    - name: Add Docker GPG apt Key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Install Docker
      become: true
      shell:
        cmd: "curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh"
      args:
        creates: /usr/bin/docker
      register: docker_installed
      when: ansible_os_family == 'Debian' # Adjust for other distributions

    - name: Install Docker Module for Python
      become: true
      pip:
        name: docker==6.1.3
      when: docker_installed.changed

    - name: Install Docker Compose Module for Python
      become: true
      pip:
        name: docker-compose
      when: docker_installed.changed

    - name: Add "azureadmin" user to "docker" group
      become: true
      user:
        name: "azureadmin"
        groups: "docker"
        append: yes
      tags:
        - docker
        
    - name: Ensure 'webapp_vote_mba' user exists
      user:
        name: webapp_vote_mba
        state: present

    - name: Copy 'docker' folder to the remote server
      become: true
      copy:
        src: ../docker/
        dest: /home/webapp_vote_mba/docker/
        owner: webapp_vote_mba
        group: webapp_vote_mba

    - name: Start services with Docker Compose
      become: true
      community.general.docker_compose:
        project_src: /home/webapp_vote_mba/docker/
        state: present
        build: yes
        restarted: yes