---
- hosts: webservers
  become: true

  tasks:
    - name: Install required system packages
      become: true
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      when: ansible_os_family == 'Debian'  # Adjust for other distributions

    - name: Install Docker
      become: true
      script: 
        cmd: "curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh"
      args:
        creates: /usr/bin/docker
      register: docker_installed
      when: ansible_os_family == 'Debian'  # Adjust for other distributions

    - name: Install Docker Module for Python
      become: true
      pip:
        name: docker==6.1.3
      when: docker_installed.changed

    - name: Install Docker Compose Module for Python
      become: true
      pip:
        name: docker-compose
      when: docker_installed.changed

    - name: Add "ubuntu" user to "docker" group
      become: true
      user:
        name: "ubuntu"
        groups: "docker"
        append: yes
      tags:
        - docker

    - name: Copy 'docker' folder to the remote server
      become: true
      copy:
        src: ../docker/
        dest: /home/ubuntu/docker/
        owner: ubuntu
        group: ubuntu

    - name: Start services with Docker Compose
      become: true
      community.general.docker_compose:
        project_src: /home/ubuntu/docker/
        state: present
        build: yes
        restarted: yes